<a href="https://colab.research.google.com/github/prashantyadla/DataScience/blob/master/Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip3 list | grep torch

torch                    1.4.0          
torchsummary             1.5.1          
torchtext                0.3.1          
torchvision              0.5.0          


In [0]:
import torch

In [0]:
x = torch.empty(5,3)
print(x)

tensor([[6.5410e-38, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 1.3312e-43],
        [6.8616e-07, 1.0680e-05, 1.6504e-07],
        [1.0921e-05, 1.0741e-05, 1.3002e+22],
        [1.0860e-05, 2.1270e-07, 5.1480e-11]])


In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)


x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7097, -0.3161, -0.5887],
        [-0.2876,  0.1520, -0.7053],
        [ 0.2340,  1.3257,  1.2295],
        [-0.3117, -0.5766,  0.3722],
        [-1.2478,  0.1151, -0.5202]])


In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
from tensorflow.python.client import device_lib

device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 11537230314921008276, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 16778470721770553328
 physical_device_desc: "device: XLA_CPU device", name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 12308665383366606989
 physical_device_desc: "device: XLA_GPU device", name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 6890635936
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 16467423669616469066
 physical_device_desc: "device: 0, name: Tesla P4, pci bus id: 0000:00:04.0, compute capability: 6.1"]

In [0]:
import tensorflow as tf
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [0]:
class Solution():
  def main(self):
    print("This is main function inside Solution class!")

In [0]:
sol = Solution()
sol.main()
# sol.__main__()
# sol.__main__()

This is main function inside Solution class!


In [0]:
def test():
  result = set()
  for i in range(1,10, 2):
    result.add(i)
  print(result)

In [0]:
test()

{1, 3, 5, 7, 9}


In [0]:
from typing import List


In [0]:
class Solution:
    def createTargetArray(self, nums: List[int], index: List[int]) -> List[int]:
      target = [None]*len(nums)
      for i in range(len(nums)):
        if(target[index[i]] == None):
          target[index[i]] = nums[i]
        else:
          temp = target[index[i]:]
          target[index[i]] = nums[i]
          target[index[i]+1:] = temp
      # print(target)
      final_target = []
      for x in target:
        if(x!=None):
          final_target.append(x)
      print(final_target)
      return final_target

In [0]:
sol = Solution()
sol.createTargetArray([1,2,3,4,0], [0,1,2,3,0])

[0, 1, 2, 3, 4]


[0, 1, 2, 3, 4]

In [0]:
x = [None]*15
print(x)
if(x[0] == None):
  print(True)

[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
True


In [0]:
# shift([1,2,3], 1)

NameError: ignored

In [0]:
target = [1,2,3,4,0]

temp = target[2:]
print(temp)

[3, 4, 0]


In [0]:
target[2] = 4
target[3:] = temp

In [0]:
target

[1, 2, 4, 3, 4, 0]

In [0]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.7068,  0.3521,  0.0319],
        [ 0.2618,  0.3704, -0.6543],
        [ 0.9306,  1.3981,  1.6532],
        [ 0.0919, -0.5186,  0.8412],
        [-0.6211,  1.0422,  0.1220]])


In [0]:
print(y.size())

torch.Size([5, 3])


In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
print(torch.add(x, y))

tensor([[ 1.7068,  0.3521,  0.0319],
        [ 0.2618,  0.3704, -0.6543],
        [ 0.9306,  1.3981,  1.6532],
        [ 0.0919, -0.5186,  0.8412],
        [-0.6211,  1.0422,  0.1220]])


In [0]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 1.7068,  0.3521,  0.0319],
        [ 0.2618,  0.3704, -0.6543],
        [ 0.9306,  1.3981,  1.6532],
        [ 0.0919, -0.5186,  0.8412],
        [-0.6211,  1.0422,  0.1220]])


In [0]:
print(x)
print(x.shape)

print(x[:, 1])

tensor([[ 0.7097, -0.3161, -0.5887],
        [-0.2876,  0.1520, -0.7053],
        [ 0.2340,  1.3257,  1.2295],
        [-0.3117, -0.5766,  0.3722],
        [-1.2478,  0.1151, -0.5202]])
torch.Size([5, 3])
tensor([-0.3161,  0.1520,  1.3257, -0.5766,  0.1151])


In [0]:
x = torch.randn(4, 4)
y = x.view(16)
print(y)

tensor([ 1.2751, -0.3131, -1.2093, -1.9624,  0.4764, -1.0187,  0.2069, -0.4743,
         0.2619,  1.4112, -0.8198,  1.2887, -1.5066,  1.7413,  1.6631, -0.8189])


In [0]:
print(x.size())

torch.Size([4, 4])


In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [0]:
a

tensor([2., 2., 2., 2., 2.])

In [0]:
interests = [
(0, "Hadoop"), (0, "Big Data"), (0, "HBase"), (0, "Java"),
(0, "Spark"), (0, "Storm"), (0, "Cassandra"),
(1, "NoSQL"), (1, "MongoDB"), (1, "Cassandra"), (1, "HBase"),
(1, "Postgres"), (2, "Python"), (2, "scikit-learn"), (2, "scipy"),
(2, "numpy"), (2, "statsmodels"), (2, "pandas"), (3, "R"), (3, "Python"), (3, "statistics"), (3, "regression"), (3, "probability"),
(4, "machine learning"), (4, "regression"), (4, "decision trees"),
(4, "libsvm"), (5, "Python"), (5, "R"), (5, "Java"), (5, "C++"),
(5, "Haskell"), (5, "programming languages"), (6, "statistics"),
(6, "probability"), (6, "mathematics"), (6, "theory"),
(7, "machine learning"), (7, "scikit-learn"), (7, "Mahout"),
(7, "neural networks"), (8, "neural networks"), (8, "deep learning"),
(8, "Big Data"), (8, "artificial intelligence"), (9, "Hadoop"),
(9, "Java"), (9, "MapReduce"), (9, "Big Data")
]

In [0]:
len(interests)


49

In [0]:
u = [x for x,y in interests]

In [0]:
print(u)

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]


In [0]:
words_and_counts = [word for user, interest in interests for word in interest.lower().split()]


In [0]:
from collections import Counter

In [0]:
words_and_counts = Counter(word for user, interest in interests for word in interest.lower().split())

In [0]:
words_and_counts.most_common()

[('big', 3),
 ('data', 3),
 ('java', 3),
 ('python', 3),
 ('learning', 3),
 ('hadoop', 2),
 ('hbase', 2),
 ('cassandra', 2),
 ('scikit-learn', 2),
 ('r', 2),
 ('statistics', 2),
 ('regression', 2),
 ('probability', 2),
 ('machine', 2),
 ('neural', 2),
 ('networks', 2),
 ('spark', 1),
 ('storm', 1),
 ('nosql', 1),
 ('mongodb', 1),
 ('postgres', 1),
 ('scipy', 1),
 ('numpy', 1),
 ('statsmodels', 1),
 ('pandas', 1),
 ('decision', 1),
 ('trees', 1),
 ('libsvm', 1),
 ('c++', 1),
 ('haskell', 1),
 ('programming', 1),
 ('languages', 1),
 ('mathematics', 1),
 ('theory', 1),
 ('mahout', 1),
 ('deep', 1),
 ('artificial', 1),
 ('intelligence', 1),
 ('mapreduce', 1)]

In [0]:
for word, count in words_and_counts.most_common():
  if(count > 1):
    print(word, count)

big 3
data 3
java 3
python 3
learning 3
hadoop 2
hbase 2
cassandra 2
scikit-learn 2
r 2
statistics 2
regression 2
probability 2
machine 2
neural 2
networks 2


In [0]:
another_double = lambda x: 2*x

def another_double(x):
  return 2*x

In [0]:
def my_print(message="my default message"):
  print(message)

my_print("hello")
my_print()

hello
my default message


In [0]:
tab_string = "\t"
print("len :- ", len(tab_string))

len :-  1


In [0]:
single_quoted_string = 'data science'
double_quoted_string = "data science"

In [0]:
tab_string = "\t"
len(tab_string)

1

In [0]:
not_tab_string = 